

consumableItems = {
    "pocaoVidaP" : {
        "Name"          :  "Pocao de Vida P",
        "Type"          :  "consumable",
        "Effects"       :  20,
        "fxTarget"      :  "Life",
        "Description"   :  "Restaura 20 de HP do Personagem",
        "Price"         :  35,
        "Stack"         :  True,
        "maxStack"      :  5,
        "Amount"        :  0  
    },
    "pocaoVidaM" : {
        "Name"          :"Pocao de Vida M",
        "Type"          : "consumable",
        "Effects"       : 40,
        "fxTarget"      : "Life",
        "Description"   : "Restaura 4O de HP do Personagem",
        "Price"         : 60,
        "Stack"         : True,
        "maxStack"      : 5, 
        "Amount"        : 0 
    },
    "pocaoVidaG" : {
        "Name"          :"Pocao de Vida G",
        "Type"          : "consumable",
        "Effects"       : 80,
        "fxTarget"      : "Life",
        "Description"   : "Restaura 80 de HP do Personagem",
        "Price"         : 120,
        "Stack"         : True,
        "maxStack"      : 5,
        "Amount"        : 0  
    }, 
    "pocaoManaP" : {
        "Name"          :"Pocao de Vida P",
        "Type"          : "consumable",
        "Effects"       : 20,
        "fxTarget"      : "Mana",
        "Description"   : "Restaura 20 de Mana do Personagem",
        "Price"         : 35,
        "Stack"         : True,
        "maxStack"      : 5,
        "Amount"        : 0  
    },
    "pocaoManaM" : {
        "Name"          :"Pocao de Vida M",
        "Type"          : "consumable",
        "Effects"       : 40,
        "fxTarget"      : "Mana",
        "Description"   : "Restaura 4O de Mana do Personagem",
        "Price"         : 60,
        "Stack"         : True,
        "maxStack"      : 5, 
        "Amount"        : 0 
    },
    "pocaoManaG" : {
        "Name"          :"Pocao de Vida G",
        "Type"          : "consumable",
        "Effects"       : 80,
        "fxTarget"      : "Mana",
        "Description"   : "Restaura 80 de Mana do Personagem",
        "Price"         : 120,
        "Stack"         : True,
        "maxStack"      : 5,
        "Amount"        : 0  
    },    
}
equpableItems = {
    "capaceteComum" : {
        "Name"      : "Capacete Comum",
        "Type"      : "equipable",
        "eqTarget"  : "Head",
        "Rarity"    : "Comum",
        "Defesa"    : 1,
        "Stack"     : False,
        "maxStack"  : 1,
        "Price"     : 60,
        "Description": "Um capacete comum que protege 8 de Dano",   
    },
    "peitoralComum" : {
        "Name"      : "Peitoral Comum",
        "Type"      : "equipable",
        "eqTarget"  : "Chest",
        "Rarity"    : "Comum",
        "Defesa"    : 2,
        "Stack"     : False,
        "maxStack"  : 1,
        "Price"     : 60,
        "Description": "Um peitoral comum que protege 8 de Dano",   
    },
    "calçaComum" : {
        "Name"      : "Calça Comum",
        "Type"      : "equipable",
        "eqTarget"  : "Legs",
        "Rarity"    : "Comum",
        "Defesa"    : 1,
        "Stack"     : False,
        "maxStack"  : 1,
        "Price"     : 60,    
        "Description": "Uma calça comum que protege 8 de Dano",
    },
    "botasComum" : {
        "Name"      : "Botas Comum",
        "Type"      : "equipable",
        "eqTarget"  : "Foots",
        "Rarity"    : "Comum",
        "Defesa"    : 1,
        "Stack"     : False,
        "maxStack"  : 1,
        "Price"     : 60,
        "Description": "Uma bota comum que protege 8 de Dano",   
    },
    "anelComum" : {
        "Name"      : "Anel Comum",
        "Type"      : "equipable",
        "eqTarget"  : "Ring",
        "Rarity"    : "Comum",
        "Efects"    : 6,
        "fxTaget"   : "DEF",
        "Stack"     : False,
        "maxStack"  : 1,
        "Price"     : 60,
        "LvL"       : 1,
        "Description": "Uma anel comum que protege 8 de Dano",     
    },
}